"""
Setting relating to the output of the spreadsheets from Swim Manager.

"""

MEMBERS_COLUMN_FIRST_NAME = 1
MEMBERS_COLUMN_LAST_NAME = 3
MEMBERS_COLUMN_DOB = 5
MEMBERS_COLUMN_GENDER = 6
MEMBERS_COLUMN_MEMBERSHIP_CATEGORY = 23
MEMBERS_COLUMN_MEMBERSHIP_NUMBER = 22  # was 21
MEMBERS_COLUMN_SQUAD_NAME = 20  # was 19
